import type { AssessmentConfig } from "../types.js";

// STAR Early Literacy / Reading (Renaissance). Scaled/Unified ≤ 1400, PR ≤ 99,
// domain scores ≤ 1000.
export const star: AssessmentConfig = {
  id: "STAR",
  displayName: "STAR Early Literacy / Reading",
  vendor: "Renaissance",
  canonicalFields: [
    { name: "student_id", label: "Student ID", type: "string", category: "student", required: true },
    { name: "student_first_name", label: "First Name", type: "string", category: "student", required: true },
    { name: "student_last_name", label: "Last Name", type: "string", category: "student", required: true },
    { name: "school_name", label: "School", type: "string", category: "student", required: true },
    { name: "grade", label: "Grade", type: "grade", category: "student", required: true },
    { name: "scaled_score", label: "Scaled Score", type: "number", category: "measure", min: 0, max: 1400, measureType: "scaled" },
    { name: "unified_score", label: "Unified Score", type: "number", category: "measure", min: 0, max: 1400, measureType: "scaled" },
    { name: "percentile_rank", label: "Percentile Rank", type: "number", category: "measure", min: 1, max: 99, measureType: "percentile" },
    { name: "grade_equivalent", label: "Grade Equivalent", type: "string", category: "measure", measureType: "classification" },
    { name: "literacy_classification", label: "Literacy Classification", type: "string", category: "measure", measureType: "classification" },
    { name: "alphabetic_decoding", label: "Alphabetic Decoding", type: "number", category: "measure", min: 0, max: 1000, measureType: "scaled" },
    { name: "visual_discrimination", label: "Visual Discrimination", type: "number", category: "measure", min: 0, max: 1000, measureType: "scaled" },
    { name: "phonemic_awareness", label: "Phonemic Awareness", type: "number", category: "measure", min: 0, max: 1000, measureType: "scaled" },
    { name: "phonics", label: "Phonics", type: "number", category: "measure", min: 0, max: 1000, measureType: "scaled" },
    { name: "structural_analysis", label: "Structural Analysis", type: "number", category: "measure", min: 0, max: 1000, measureType: "scaled" },
    { name: "vocabulary", label: "Vocabulary", type: "number", category: "measure", min: 0, max: 1000, measureType: "scaled" },
    { name: "sentence_level_comprehension", label: "Sentence-Level Comprehension", type: "number", category: "measure", min: 0, max: 1000, measureType: "scaled" },
    { name: "paragraph_level_comprehension", label: "Paragraph-Level Comprehension", type: "number", category: "measure", min: 0, max: 1000, measureType: "scaled" },
  ],
  synonymMap: {
    "student id": "student_id", "sis id": "student_id", "lasid": "student_id", "id": "student_id",
    "first name": "student_first_name", "fname": "student_first_name", "student first name": "student_first_name",
    "last name": "student_last_name", "lname": "student_last_name", "student last name": "student_last_name",
    "school name": "school_name", "school": "school_name",
    "grade level": "grade", "grade": "grade",
    "scaled score": "scaled_score", "ss": "scaled_score", "star scaled score": "scaled_score",
    "unified score": "unified_score",
    "percentile rank": "percentile_rank", "pr": "percentile_rank", "national percentile rank": "percentile_rank",
    "grade equivalent": "grade_equivalent", "ge": "grade_equivalent",
    "literacy classification": "literacy_classification",
    "alphabetic decoding": "alphabetic_decoding",
    "visual discrimination": "visual_discrimination",
    "phonemic awareness": "phonemic_awareness",
    "phonics": "phonics",
    "structural analysis": "structural_analysis",
    "vocabulary": "vocabulary",
    "sentence-level comprehension": "sentence_level_comprehension", "sentence level comprehension": "sentence_level_comprehension",
    "paragraph-level comprehension": "paragraph_level_comprehension", "paragraph level comprehension": "paragraph_level_comprehension",
  },
  requiredByGrade: {},
  performanceLevels: {
    "At/Above Benchmark": "Above Benchmark",
    "At/Above": "Above Benchmark",
    "On Watch": "Near Benchmark",
    Intervention: "Below Benchmark",
    "Urgent Intervention": "Below Benchmark",
  },
  crossFieldChecks: [],
};
